default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myblog_development

test:
  <<: *default
  database: myblog_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000

