default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_afso
  username: blog_afso_user
  password: ylpN2tmO68oqbLOHm5yXXkSOOQQOgJjG
  host: dpg-cs256rl6l47c73bc7cn0-a
  port: 5432

test:
  <<: *default
  database: blog_afso
  username: blog_afso_user
  password: ylpN2tmO68oqbLOHm5yXXkSOOQQOgJjG
  host: dpg-cs256rl6l47c73bc7cn0-a
  port: 5432

production:
  <<: *default
  url: <%= ENV['postgresql://blog_afso_user:ylpN2tmO68oqbLOHm5yXXkSOOQQOgJjG@dpg-cs256rl6l47c73bc7cn0-a/blog_afso'] %>
