databases:
  - name: blog_afso
    databaseName: blog_afso
    user: blog_afso_user
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake db:migrate && bundle exec rake assets:precompile"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2

